framework:
    workflows:
        book_status:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'status'
            supports:
                - AppBundle\Entity\Book
            places:
                - free
                - reserved
                - taken
            transitions:
                to_free:
                    from: [taken, reserved]
                    to: free
                to_taken:
                    from: [free, reserved]
                    to: taken
                to_reserved:
                    from: free
                    to: reserved